import React,{Component} from 'react';
export class History extends Component{
    render(){
        return(
            <section>
<form>
<div className="history">
<h2>Indian Clothing Online Shopping for Women &amp; Men</h2>
<p>During 2500 BC, India became one of the first places to grow and use cotton for making clothes. Human art forms in Indian temples and monuments are perhaps the main source of information on Indian clothing. Apart from that the rock-cut sculptures, the cave paintings, and remains from the sites of Indus Valley civilization also give a detailed bureau of clothing trends in India.</p>
<p>A large majority of Indian clothing for men and women has evolved from garments like langota, lungi, sari, gamcha, and dhoti. India is the second most populous country in the world and it shows great diversity in its population as well. Clothing in India is greatly influenced by the religion people follow.</p>
<p>The most notable ethnic apparel for men in India is the kurta pyjama. The <a href="#"><strong>sherwani</strong></a> is an iteration of the kurta pyjama and is mainly worn during the wedding. However, the kurta pyjama is an iteration of the jama dhoti which was worn by men India in the 19th century. It is still worn regularly by men in rural areas and occasionally by men in urban areas during festive occasions.</p>
<p>Apart from the <a href="#"><strong>dhoti</strong></a>, ethnic Indian wear also consists of the sarong which is more commonly known as the lungi. It is a piece of cloth that men drape around the waist and tie it. It is usually worn by Muslim men. But a large majority of men in South and East India can be seen sporting the lungi. It comes in different patterns and colors but the length of the cloth is usually constant.</p>
<p>The sherwani is another Indian ethnic wear. The ethnic name of this garment is achkan. It is essentially a kurta made in the form of a jacket with exposed button, heavy embroidery and needlework. The sherwani flows just below the knees and is usually paired with pants called churidar. As a matter of fact, churidars are also worn by Indian women.</p>
<p>The bandhgala is an iteration of the sherwani. Bandh means closed and gala means neck. The name suggests that the garment sports a closed neck design or what many people like to call as the mandarin collar design. This garment hails from the royal land of Jodhpur. The pants worn with this are baggy throughout the hip and thigh region and grasp the legs tightly. This Indian ethnic wear gain popularity quickly and a large majority of men wear this outfit during festivals, weddings, and special occasions</p>
<p>Sarees are indeed the most popular <a href="#"><strong>Indian ethnic wear</strong></a> for women. A saree is basically a long piece of cloth, usually around 10 meters long which is draped around the body in a variety of different styles.  Different regions have a special type of saree, for example, Kanchipuram from South India, Paithani from Maharashtra, Benarasi from North India, and Muga Silk from Assam. A blouse is worn with the saree which is called the choli.</p> 
<p>The <a href="#"><strong>saree</strong></a> is very popular in all parts of India and so is the salwar kameez. The kameez is basically a kurti and the salwar is the lower garment. It is traditionally worn by women in Punjab and hence, it is also sometimes referred to as the Punjabi Suit. There are different iterations of the salwar kameez. The Anarkali suit, palazzo suit, Patiala suit etc. are some of the different kinds of suits available.  Dupatta is worn along with salwar kameez. It is called the odani in some parts of India and is mainly used to veil the head in the presence of elders.
Change in fashion trends has bought in various types of <a href="#"><strong>salwars</strong></a> like dhoti salwar, churidars, Patiala salwars, Afghani Salwars, Palazzo and so on.</p> 
<h2>Traditional Clothing of India</h2>
<p>Traditional Indian clothing depends largely on the religious group that people follow. Followers of Islam probably have the most distinct outfits. Islam guides that men and women must dress modestly. <a href="/islamic-clothing"><strong>Islamic clothing</strong></a> is all about modesty. Both men and women have certain rules on what they can wear and what they can’t. One distinctive feature of the Islamic pant is that they are airy and comfortable.</p>
<p>Serwal is one of the most prevalent pant types in Muslim culture. A large majority of Muslim men have at least 1 serwal in their wardrobe. The serwal is made from cotton and is mostly worn beneath the thobe. Men can also pair it with a white shirt. The serwal also doubles down as a pyjama. It is very comfortable and can be worn easily at home. It is available in the elastic waist, drawstring waist, or a combination of both. In Islamic culture, the serwal is better known as mikasser.</p>
<p>Muslim men also wear the izar which is an iteration of the lungi/sarong. For Muslim women, the burka, <a href="/islamic-clothing/hijab"><strong>hijab</strong></a> and abaya are staples. The hijab is a cloth which is used to cover the head, the abaya is a free-flowing cloak from head to toe and the burka covers the head and the chest region. Men and women that follow Hinduism wear kurta pyjama and sarees mainly. Regional diversity also comes into play when talking about <a href="/women/clothing/indian-dresses"><strong>traditional Indian clothing</strong></a>.</p> 
<p>Therefore, the Indian clothing history is very rich and the future of Indian fashion also looks pretty bright with all the fashion designers around. Get the fashion trend outfits at Mirraw <a href="/"><strong>online shopping</strong></a> site with amazing options and cool price</p>
</div>
</form>
</section>

        );
    }
}